name: "Gitflow Workflow Action"
description: "Create PR for release + Create GH release and send Slack message on merge"

inputs:
  version:
    description: The version to be released
    required: false
    default: ""
  develop_branch:
    description: The branch used for development
    required: true
  main_branch:
    description: The branch used for production
    required: true
  release_prefix:
    description: release branch prefix
    required: false
    default: "release/"
  hotfix_prefix:
    description: hotfix branch prefix
    required: false
    default: "hotfix/"
  slack:
    description: The slack options (channel, name mapping)
    required: false

runs:
  using: "node16"
  main: "dist/index.js"
